version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: stable
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      safe-npm-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: stable
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
